# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class FastAPI:
        name: str
        type: str
        url: str
    class MyLinkableValue:
        foo: str
        type: str

